"""
src/features.py
===============
Feature engineering module for candidate pairs.

Takes candidate pairs generated by `blocking.py` and computes lexical,
categorical, and retrieval-based features for use in a downstream model
like LightGBM.

Features are computed using `rapidfuzz` for fast string similarity.
No external data, pretrained models, or ground-truth leakage is permitted.
"""

import logging
from typing import List

import numpy as np
import pandas as pd
from rapidfuzz import fuzz
from rapidfuzz.distance import JaroWinkler

from src.config import cfg, PipelineConfig
from src.blocking import (
    COL_S1_ID, COL_CAND_ID, COL_CAND_SRC,
    COL_EX_NAME, COL_EX_ADDR, COL_NG_NAME, COL_NG_ADDR,
    COL_NG_NAME_SC, COL_NG_ADDR_SC, COL_PASS_COUNT,
    SOURCE_S2, SOURCE_S3
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Feature Column Definitions
# ---------------------------------------------------------------------------

# Missingness
F_NAME_MISS_S1 = "name_missing_s1"
F_NAME_MISS_CAND = "name_missing_cand"
F_ADDR_MISS_S1 = "addr_missing_s1"
F_ADDR_MISS_CAND = "addr_missing_cand"
F_CTRY_MISS_S1 = "ctry_missing_s1"
F_CTRY_MISS_CAND = "ctry_missing_cand"

# Name features
F_NAME_EXACT = "name_exact"
F_NAME_JARO = "name_jaro"
F_NAME_FUZZ = "name_fuzz_ratio"
F_NAME_TOKEN = "name_token_set_ratio"
F_NAME_LEN_S1 = "name_len_s1"
F_NAME_LEN_CAND = "name_len_cand"
F_NAME_LEN_DIFF = "name_len_diff_abs"
F_NAME_LEN_RATIO = "name_len_ratio"

# Address features
F_ADDR_EXACT = "addr_exact"
F_ADDR_JARO = "addr_jaro"
F_ADDR_FUZZ = "addr_fuzz_ratio"
F_ADDR_TOKEN = "addr_token_set_ratio"
F_ADDR_LEN_S1 = "addr_len_s1"
F_ADDR_LEN_CAND = "addr_len_cand"
F_ADDR_LEN_DIFF = "addr_len_diff_abs"
F_ADDR_LEN_RATIO = "addr_len_ratio"

# Country features
F_CTRY_EXACT = "ctry_exact"

# Source features
F_IS_S2 = "is_source_s2"
F_IS_S3 = "is_source_s3"

# Candidate flags / Retrieval features (carried over)
F_FROM_EX_NAME = "f_from_exact_name"
F_FROM_EX_ADDR = "f_from_exact_address"
F_FROM_NG_NAME = "f_from_ngram_name"
F_FROM_NG_ADDR = "f_from_ngram_address"
F_NG_NAME_SCORE = "f_ngram_name_score"
F_NG_ADDR_SCORE = "f_ngram_address_score"
F_PASS_COUNT = "f_retrieval_pass_count"


def get_feature_columns() -> List[str]:
    """
    Returns the exact list of feature columns that should be fed into
    the model. This explicitly excludes identity columns like entity_ids.
    """
    return [
        F_NAME_MISS_S1, F_NAME_MISS_CAND,
        F_ADDR_MISS_S1, F_ADDR_MISS_CAND,
        F_CTRY_MISS_S1, F_CTRY_MISS_CAND,
        
        F_NAME_EXACT, F_NAME_JARO, F_NAME_FUZZ, F_NAME_TOKEN,
        F_NAME_LEN_S1, F_NAME_LEN_CAND, F_NAME_LEN_DIFF, F_NAME_LEN_RATIO,
        
        F_ADDR_EXACT, F_ADDR_JARO, F_ADDR_FUZZ, F_ADDR_TOKEN,
        F_ADDR_LEN_S1, F_ADDR_LEN_CAND, F_ADDR_LEN_DIFF, F_ADDR_LEN_RATIO,
        
        F_CTRY_EXACT,
        F_IS_S2, F_IS_S3,
        
        F_FROM_EX_NAME, F_FROM_EX_ADDR, F_FROM_NG_NAME, F_FROM_NG_ADDR,
        F_NG_NAME_SCORE, F_NG_ADDR_SCORE, F_PASS_COUNT
    ]


# ---------------------------------------------------------------------------
# Feature Engineering
# ---------------------------------------------------------------------------

def _compute_string_features(s1_str: pd.Series, cand_str: pd.Series, prefix: str) -> pd.DataFrame:
    """
    Compute string similarities and length metrics between two series.
    Returns a DataFrame of computed features.
    """
    # Replace NaNs with empty string
    s1_clean = s1_str.fillna("")
    cand_clean = cand_str.fillna("")

    # Length features
    len_s1 = s1_clean.str.len()
    len_cand = cand_clean.str.len()
    len_diff = (len_s1 - len_cand).abs()
    
    # Safe length ratio: min(len) / max(len) -> 1.0 if identical length, 0.0 if one is empty
    len_max = np.maximum(len_s1, len_cand)
    len_min = np.minimum(len_s1, len_cand)
    len_ratio = np.where(len_max > 0, len_min / len_max, 0.0)

    # Missingness
    miss_s1 = (len_s1 == 0).astype(np.float32)
    miss_cand = (len_cand == 0).astype(np.float32)
    
    # Exact match
    exact = (s1_clean == cand_clean) & (len_s1 > 0)

    # Similarities (apply row-wise)
    # Using np.vectorize or zip for performance over raw apply
    def calc_jaro(a, b):
        return JaroWinkler.normalized_similarity(a, b) if a and b else 0.0
        
    def calc_fuzz(a, b):
        return fuzz.ratio(a, b) / 100.0 if a and b else 0.0
        
    def calc_token(a, b):
        return fuzz.token_set_ratio(a, b) / 100.0 if a and b else 0.0

    jaro_vals = [calc_jaro(a, b) for a, b in zip(s1_clean, cand_clean)]
    fuzz_vals = [calc_fuzz(a, b) for a, b in zip(s1_clean, cand_clean)]
    token_vals = [calc_token(a, b) for a, b in zip(s1_clean, cand_clean)]

    df = pd.DataFrame({
        f"{prefix}_missing_s1": miss_s1.astype(np.int8),
        f"{prefix}_missing_cand": miss_cand.astype(np.int8),
        f"{prefix}_exact": exact.astype(np.int8),
        f"{prefix}_len_s1": len_s1.astype(np.int16),
        f"{prefix}_len_cand": len_cand.astype(np.int16),
        f"{prefix}_len_diff_abs": len_diff.astype(np.int16),
        f"{prefix}_len_ratio": len_ratio.astype(np.float32),
        f"{prefix}_jaro": np.array(jaro_vals, dtype=np.float32),
        f"{prefix}_fuzz_ratio": np.array(fuzz_vals, dtype=np.float32),
        f"{prefix}_token_set_ratio": np.array(token_vals, dtype=np.float32),
    }, index=s1_str.index)

    return df


def generate_features(
    s1: pd.DataFrame,
    s2: pd.DataFrame,
    s3: pd.DataFrame,
    candidates: pd.DataFrame,
    config: PipelineConfig = cfg,
) -> pd.DataFrame:
    """
    Generate the complete feature matrix for all candidate pairs,
    using pre-allocated arrays to strictly bound memory.
    """
    feature_cols = get_feature_columns()
    if candidates.empty:
        cols = [COL_S1_ID, COL_CAND_ID, COL_CAND_SRC] + feature_cols
        return pd.DataFrame(columns=cols)

    logger.info("Generating features for %d candidates", len(candidates))
    from src.config import log_memory
    import gc

    # 1. Setup indices for fast lookup
    eid_col = config.COL_ENTITY_ID
    needed_cols = [eid_col, config.COL_NAME_NORM, config.COL_ADDRESS_NORM, config.COL_COUNTRY_NORM]
    
    s1_indexed = s1[needed_cols].set_index(eid_col)
    s2_indexed = s2[needed_cols].set_index(eid_col)
    s3_indexed = s3[needed_cols].set_index(eid_col)

    # 2. Pre-allocate the massive feature array to prevent concat spikes
    num_cands = len(candidates)
    num_feats = len(feature_cols)
    out_features = np.empty((num_cands, num_feats), dtype=np.float32)
    
    batch_size = config.MAX_FEATURE_BATCH_SIZE
    
    log_memory("Before feature loop")

    for start_idx in range(0, num_cands, batch_size):
        end_idx = min(start_idx + batch_size, num_cands)
        chunk = candidates.iloc[start_idx : end_idx].copy()
        
        # 3. Join S1 data
        s1_data = s1_indexed.loc[chunk[COL_S1_ID]].reset_index(drop=True)
        
        # 4. Join Candidate data (S2 or S3)
        cand_ids = chunk[COL_CAND_ID].values
        cand_srcs = chunk[COL_CAND_SRC].values
        
        mask_s2 = (cand_srcs == SOURCE_S2)
        mask_s3 = (cand_srcs == SOURCE_S3)
        
        cand_name = np.empty(len(chunk), dtype=object)
        cand_addr = np.empty(len(chunk), dtype=object)
        cand_ctry = np.empty(len(chunk), dtype=object)
        
        if mask_s2.any():
            s2_subset = s2_indexed.loc[cand_ids[mask_s2]].reset_index(drop=True)
            cand_name[mask_s2] = s2_subset[config.COL_NAME_NORM].values
            cand_addr[mask_s2] = s2_subset[config.COL_ADDRESS_NORM].values
            cand_ctry[mask_s2] = s2_subset[config.COL_COUNTRY_NORM].values
            
        if mask_s3.any():
            s3_subset = s3_indexed.loc[cand_ids[mask_s3]].reset_index(drop=True)
            cand_name[mask_s3] = s3_subset[config.COL_NAME_NORM].values
            cand_addr[mask_s3] = s3_subset[config.COL_ADDRESS_NORM].values
            cand_ctry[mask_s3] = s3_subset[config.COL_COUNTRY_NORM].values
            
        cand_name_s = pd.Series(cand_name, dtype=object, index=chunk.index)
        cand_addr_s = pd.Series(cand_addr, dtype=object, index=chunk.index)
        cand_ctry_s = pd.Series(cand_ctry, dtype=object, index=chunk.index)
            
        # 5. Compute Name Features
        name_feats = _compute_string_features(
            s1_data[config.COL_NAME_NORM], 
            cand_name_s, 
            prefix="name"
        )
        
        # 6. Compute Address Features
        addr_feats = _compute_string_features(
            s1_data[config.COL_ADDRESS_NORM], 
            cand_addr_s, 
            prefix="addr"
        )
        
        # 7. Compute Country Features
        s1_ctry = s1_data[config.COL_COUNTRY_NORM].fillna("")
        cand_ctry_series = cand_ctry_s.fillna("")
        
        ctry_miss_s1 = (s1_ctry == "").astype(np.float32)
        ctry_miss_cand = (cand_ctry_series == "").astype(np.float32)
        ctry_exact = ((s1_ctry == cand_ctry_series) & (s1_ctry != "")).astype(np.float32)
        
        # 8. Source Indicators
        is_s2 = mask_s2.astype(np.float32)
        is_s3 = mask_s3.astype(np.float32)
        
        # 9. Retrieval Features
        ret_ex_name = chunk.get(COL_EX_NAME, pd.Series(False, index=chunk.index)).astype(np.float32)
        ret_ex_addr = chunk.get(COL_EX_ADDR, pd.Series(False, index=chunk.index)).astype(np.float32)
        ret_ng_name = chunk.get(COL_NG_NAME, pd.Series(False, index=chunk.index)).astype(np.float32)
        ret_ng_addr = chunk.get(COL_NG_ADDR, pd.Series(False, index=chunk.index)).astype(np.float32)
        ret_ng_name_sc = chunk.get(COL_NG_NAME_SC, pd.Series(0.0, index=chunk.index)).astype(np.float32)
        ret_ng_addr_sc = chunk.get(COL_NG_ADDR_SC, pd.Series(0.0, index=chunk.index)).astype(np.float32)
        ret_pass = chunk.get(COL_PASS_COUNT, pd.Series(0.0, index=chunk.index)).astype(np.float32)
        
        # Assemble feature columns for this chunk into a fast matrix
        # MUST exactly match the order of get_feature_columns()
        chunk_vals = np.column_stack([
            name_feats["name_missing_s1"].values,
            name_feats["name_missing_cand"].values,
            addr_feats["addr_missing_s1"].values,
            addr_feats["addr_missing_cand"].values,
            ctry_miss_s1, ctry_miss_cand,
            
            name_feats["name_exact"].values,
            name_feats["name_jaro"].values,
            name_feats["name_fuzz_ratio"].values,
            name_feats["name_token_set_ratio"].values,
            name_feats["name_len_s1"].values,
            name_feats["name_len_cand"].values,
            name_feats["name_len_diff_abs"].values,
            name_feats["name_len_ratio"].values,
            
            addr_feats["addr_exact"].values,
            addr_feats["addr_jaro"].values,
            addr_feats["addr_fuzz_ratio"].values,
            addr_feats["addr_token_set_ratio"].values,
            addr_feats["addr_len_s1"].values,
            addr_feats["addr_len_cand"].values,
            addr_feats["addr_len_diff_abs"].values,
            addr_feats["addr_len_ratio"].values,
            
            ctry_exact, is_s2, is_s3,
            
            ret_ex_name, ret_ex_addr, ret_ng_name, ret_ng_addr,
            ret_ng_name_sc, ret_ng_addr_sc, ret_pass
        ])
        
        # Place directly into the pre-allocated matrix
        out_features[start_idx : end_idx, :] = chunk_vals
        
        del chunk, s1_data, cand_name, cand_addr, cand_ctry
        del name_feats, addr_feats, chunk_vals
        
        if (start_idx // batch_size) % 10 == 0:
            gc.collect()

    log_memory("After feature loop")

    # Wrap the single pre-allocated numpy array in a DataFrame (zero copy)
    final_df = pd.DataFrame(out_features, columns=feature_cols, copy=False)
    
    # Re-attach the non-feature identity columns
    final_df[COL_S1_ID] = candidates[COL_S1_ID].values
    final_df[COL_CAND_ID] = candidates[COL_CAND_ID].values
    final_df[COL_CAND_SRC] = candidates[COL_CAND_SRC].values
    
    # Reorder to standard format
    expected_cols = [COL_S1_ID, COL_CAND_ID, COL_CAND_SRC] + feature_cols
    final_df = final_df[expected_cols]
    
    logger.info("Feature engineering complete. Shape: %s", final_df.shape)
    return final_df
